### ISSUE TITLE
"ReportingServicesMgmt.cs"

### ISSUE THREAD

**Issue by umbrodomini** [dapaxx/reportsync#1]
Hi,

I tried to compile the code but its referencing "ReportingServicesMgmt.cs", am I doing something wrong? or lacking a step? please help.

Thanks.

Dennis.

**Comment by AlidaMeira** [comment]
Hi,

I have the same error. Any solution?

Thanx

**Comment by dapaxx** [comment]
I'm sorry, the file wasn't pushed to the repository.
Should be there now.

**Comment by AlidaMeira** [comment]
THANK YOU!!!!!!!!!!!!!!!!!!! YAY!!!!!!!!!!!!!!!
